<?php
        defined('BASEPATH') OR exit('No direct script access allowed');
class Migration_Init extends CI_Migration{
    public function up(){
        $sql=<<<SQL

        -- Created by Vertabelo (http://vertabelo.com)
        -- Last modification date: 2018-09-02 03:00:33.788

        -- tables
        -- Table: M_LEVEL
        CREATE TABLE M_LEVEL (
            LEVEL_ID int  NOT NULL,
            LEVEL_NAME varchar(25) NULL,
            CONSTRAINT M_LEVEL_pk PRIMARY KEY (LEVEL_ID)
        );

        INSERT INTO M_LEVEL(LEVEL_ID, LEVEL_NAME) VALUES (1, 'Beginner');
        INSERT INTO M_LEVEL(LEVEL_ID, LEVEL_NAME) VALUES (2, 'Intermediate');
        INSERT INTO M_LEVEL(LEVEL_ID, LEVEL_NAME) VALUES (3, 'Advanced');

        -- Table: M_USER
        CREATE TABLE M_USER (
            USER_ID serial  NOT NULL,
            USER_NAME varchar(25) NULL,
            EMAIL varchar(255) NULL,
            PASSWORD text NULL,
            BIRTH_DATE varchar(10) NULL,
            GENDER varchar(15) NULL,
            PHONE_NUMBER int NULL,
            ADDRESS varchar(255) NULL,
            ADMIN_FLAG char(1) NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT M_USER_pk PRIMARY KEY (USER_ID)
        );

        -- Table: TBL_ANSWER
        CREATE TABLE TBL_ANSWER (
            ANSWER_ID serial  NOT NULL,
            QUESTION_ID serial NOT NULL,
            USER_ID serial NOT NULL,
            ANSWER_NUMBER int NULL,
            ANSWER_NAME text NULL,
            ANSWER_RESULT int NULL,
            CONSTRAINT TBL_ANSWER_pk PRIMARY KEY (ANSWER_ID)
        );

        -- Table: TBL_ANSWER_QA
        CREATE TABLE TBL_ANSWER_QA (
            ANSWER_QA_ID serial  NOT NULL,
            ANSWER_QA_NAME text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_ANSWER_QA_pk PRIMARY KEY (ANSWER_QA_ID)
        );

        -- Table: TBL_EXAM
        CREATE TABLE TBL_EXAM (
            EXAM_ID serial  NOT NULL,
            LEVEL_ID int  NOT NULL,
            QUESTION_ID serial  NOT NULL,
            EXAM_NAME varchar(50) NULL,
            NUMERICAL_NAME char(2) NULL,
            CONSTRAINT TBL_EXAM_pk PRIMARY KEY (EXAM_ID)
        );

        -- Table: TBL_GRAMMAR
        CREATE TABLE TBL_GRAMMAR (
            GRAMMAR_ID serial  NOT NULL,
            LEVEL_ID int  NOT NULL,
            GRAMMAR_NAME varchar(50) NULL,
            GRAMMAR_DETAILS text NULL,
            DEL_FLAG char(1) NULL,
            CONSTRAINT TBL_GRAMMAR_pk PRIMARY KEY (GRAMMAR_ID)
        );

        -- Table: TBL_LEARN_VOCABULARY
        CREATE TABLE TBL_LEARN_VOCABULARY (
            LEARN_VOCABULARY_ID int  NOT NULL,
            LEVEL_ID int  NOT NULL,
            VOCABULARY_NAME varchar(20) NULL,
            VOCABULARY_MEAN varchar(80) NULL,
            UNIT_ID int NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_LEARN_VOCABULARY_pk PRIMARY KEY (LEARN_VOCABULARY_ID)
        );

        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (1, 1, 'a', 'Một', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (2, 1, 'an', 'Một', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (3, 1, 'about', 'Về', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (4, 1, 'above', 'Ở trên', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (5, 1, 'across', 'Ngang qua', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (6, 1, 'act', 'Hành động, cư xử', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (7, 1, 'active', 'Năng động, chủ động', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (8, 1, 'activity', 'Hoạt động', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (9, 1, 'add', 'Thêm vào, cộng', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (10, 1, 'afraid', 'Sợ, e rằng', 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (11, 1, 'after', 'Sau', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (12, 1, 'again', 'Lại, một lần nữa', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (13, 1, 'age', 'Tuổi', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (14, 1, 'ago', 'Trước đây, về trước', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (15, 1, 'agree', 'Đồng ý', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (16, 1, 'air', 'Không khí, không trung', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (17, 1, 'all', 'Tất cả, toàn bộ', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (18, 1, 'alone', 'Một mình', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (19, 1, 'along', 'Dọc theo', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (20, 1, 'already', 'đã, rồi', 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (21, 1, 'always', 'Luôn luôn', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (22, 1, 'am', 'Là', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (23, 1, 'are', 'Là', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (24, 1, 'amount', 'Lượng', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (25, 1, 'and', 'Và', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (26, 1, 'angry', 'Giận dữ', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (27, 1, 'any', 'Một vài, một số', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (28, 1, 'anyone', 'Người nào, ai', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (29, 1, 'anything', 'Vật gì, việc gì', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (30, 1, 'anytime', 'Bất kì lúc nào', 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (31, 1, 'another', 'Khác, nữa', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (32, 1, 'answer', 'Trả lời, câu trả lời', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (33, 1, 'appear', 'Xuất hiện', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (34, 1, 'apple', 'Quả táo', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (35, 1, 'area', 'Khu vực', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (36, 1, 'arm', 'Cánh tay', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (37, 1, 'army', 'Quân đội', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (38, 1, 'around', 'Vòng quanh, xung quanh', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (39, 1, 'arrive', 'Đến', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (40, 1, 'art', 'Nghệ thuật', 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (41, 1, 'as', 'Khi', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (42, 1, 'ask', 'Hỏi', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (43, 1, 'at', 'Ở, tại', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (44, 1, 'attack', 'Tấn công', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (45, 1, 'aunt', 'Dì, cô, bác', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (46, 1, 'autumn', 'Mùa thu', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (47, 1, 'away', 'Xa, cách xa', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (48, 1, 'baby', 'Trẻ con', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (49, 1, 'back', 'Sau, trở lại', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (50, 1, 'bad', 'Tồi tệ', 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (51, 1, 'bag', 'Túi', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (52, 1, 'ball', 'Bóng', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (53, 1, 'bank', 'Ngân hàng', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (54, 1, 'basket', 'Giỏ', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (55, 1, 'bath', 'Tắm', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (56, 1, 'bean', 'Đậu, đỗ', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (57, 1, 'bear', 'Gấu', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (58, 1, 'beer', 'Bia', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (59, 1, 'bed', 'giường', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (60, 1, 'bedroom', 'Phòng ngủ', 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (61, 1, 'be', 'Thì, là', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (62, 1, 'behave', 'Cư xử, hành vi', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (63, 1, 'before', 'Trước', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (64, 1, 'begin', 'Bắt đầu', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (65, 1, 'behind', 'Đằng sau', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (66, 1, 'below', 'Ở dưới', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (67, 1, 'besides', 'Ngoài, bên cạnh', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (68, 1, 'best', 'Tốt nhất', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (69, 1, 'better', 'Tốt hơn', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (70, 1, 'between', 'Ở giữa', 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (71, 1, 'bell', 'Chuông', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (72, 1, 'big', 'To, lớn', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (73, 1, 'bird', 'Con chim', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (74, 1, 'birth', 'Sự sinh đẻ', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (75, 1, 'birthday', 'Sinh nhật', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (76, 1, 'bit', 'Một mẩu, một mảnh, một ít', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (77, 1, 'bite', 'Cắn', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (78, 1, 'black', 'Màu đen', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (79, 1, 'bleed', 'Chảy máu', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (80, 1, 'blood', 'Máu', 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (81, 1, 'block', 'Khối, tòa nhà', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (82, 1, 'blue', 'Màu xanh da trời', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (83, 1, 'board', 'Bảng', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (84, 1, 'boat', 'Thuyền', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (85, 1, 'body', 'Cơ thể', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (86, 1, 'bone', 'Xương', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (87, 1, 'book', 'Sách', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (88, 1, 'border', 'Biên giới', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (89, 1, 'bottle', 'Chai, lọ', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (90, 1, 'bowl', 'Bát', 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (91, 1, 'born', 'Sinh ra', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (92, 1, 'blow', 'Thổi', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (93, 1, 'boil', 'Đun, sôi', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (94, 1, 'borrow', 'Mượn', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (95, 1, 'breathe', 'Thở', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (96, 1, 'bring', 'Mang', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (97, 1, 'brush', 'Chải (tóc), quét, đánh (răng)', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (98, 1, 'build', 'Xây dựng', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (99, 1, 'burn', 'Cháy', 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, DEL_FG) VALUES (100, 1, 'buy', 'Mua', 10, '0');

        -- Table: TBL_UNIT
        CREATE TABLE TBL_UNIT(
            UNIT_ID int NOT NULL,
            UNIT_NAME varchar(20) NULL,
            CONSTRAINT TBL_UNIT_pk PRIMARY KEY (UNIT_ID)
        );

        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (1, 'UNIT 1');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (2, 'UNIT 2');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (3, 'UNIT 3');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (4, 'UNIT 4');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (5, 'UNIT 5');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (6, 'UNIT 6');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (7, 'UNIT 7');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (8, 'UNIT 8');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (9, 'UNIT 9');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (10, 'UNIT 10');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (11, 'UNIT 11');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (12, 'UNIT 12');

        -- Table: TBL_LISTENING
        CREATE TABLE TBL_LISTENING (
            LISTENING_ID serial  NOT NULL,
            LEVEL_ID int  NOT NULL,
            LISTENING_NAME varchar(50) NULL,
            LINK_MEDIA text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_LISTENING_pk PRIMARY KEY (LISTENING_ID)
        );

        -- Table: TBL_MARK
        CREATE TABLE TBL_MARK (
            QUESTION_ID serial  NOT NULL,
            MARK int NULL
        );

        -- Table: TBL_QA
        CREATE TABLE TBL_QA (
            QA_ID serial  NOT NULL,
            USER_ID serial  NOT NULL,
            QA_ANSWER_ID serial  NOT NULL,
            QA_QUESTION_ID serial  NOT NULL,
            CONSTRAINT TBL_QA_pk PRIMARY KEY (QA_ID)
        );

        -- Table: TBL_QUESTION
        CREATE TABLE TBL_QUESTION (
            QUESTION_ID serial  NOT NULL,
            NUMBER_QUESTION int NULL,
            EXAM_ID serial  NOT NULL,
            QUESTION_NAME varchar(255) NULL,
            QUESTION_SUBTEXT text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_QUESTION_pk PRIMARY KEY (QUESTION_ID)
        );

        -- Table: TBL_QUESTION_QA
        CREATE TABLE TBL_QUESTION_QA (
            QUESTION_QA_ID serial  NOT NULL,
            QUESTION_QA_NAME text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_QUESTION_QA_pk PRIMARY KEY (QUESTION_QA_ID)
        );

        -- Table: TBL_RESULT_USER_CHOICE_ANSWER
        CREATE TABLE TBL_RESULT_USER_CHOICE_ANSWER (
            ANSWER_ID serial  NOT NULL,
            RESULT_USER_CHOICE_ANSWER int NULL
        );

        -- Table: TBL_USER_MARK
        CREATE TABLE TBL_USER_MARK (
            USER_ID serial  NOT NULL,
            QUESTION_ID serial  NOT NULL,
            USER_MARK int NULL
        );

        -- Table: TBL_VOCABULARY_PICTURE
        CREATE TABLE TBL_VOCABULARY_PICTURE (
            VOCABULARY_PICTURE_ID serial  NOT NULL,
            VOCABULARY_NAME varchar(25) NULL,
            VOCABULARY_LINK_PICTURE text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_VOCABULARY_PICTURE_pk PRIMARY KEY (VOCABULARY_PICTURE_ID)
        );

        -- Table: TBL_WORD_DICTIONARY
        CREATE TABLE TBL_WORD_DICTIONARY (
            WORD_ID serial  NOT NULL,
            WORD_NAME varchar(20) NULL,
            WORD_DETAILS text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_WORD_DICTIONARY_pk PRIMARY KEY (WORD_ID)
        );

        -- Table: TBL_WORD_HISTORY_USER
        CREATE TABLE TBL_WORD_HISTORY_USER (
            WORD_HISTORY_USER_ID serial  NOT NULL,
            USER_ID serial  NOT NULL,
            WORD_ID serial  NOT NULL,
            WORD_NAME varchar(20) NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_WORD_HISTORY_USER_pk PRIMARY KEY (WORD_HISTORY_USER_ID)
        );

        -- foreign keys
        -- Reference: TBL_ANSWER_M_USER (table: TBL_ANSWER)
        ALTER TABLE TBL_ANSWER ADD CONSTRAINT TBL_ANSWER_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_ANSWER_TBL_QUESTION (table: TBL_ANSWER)
        ALTER TABLE TBL_ANSWER ADD CONSTRAINT TBL_ANSWER_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_EXAM_M_LEVEL (table: TBL_EXAM)
        ALTER TABLE TBL_EXAM ADD CONSTRAINT TBL_EXAM_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_EXAM_TBL_QUESTION (table: TBL_EXAM)
        ALTER TABLE TBL_EXAM ADD CONSTRAINT TBL_EXAM_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_GRAMMAR_M_LEVEL (table: TBL_GRAMMAR)
        ALTER TABLE TBL_GRAMMAR ADD CONSTRAINT TBL_GRAMMAR_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_LEARN_VOCABULARY_M_LEVEL (table: TBL_LEARN_VOCABULARY)
        ALTER TABLE TBL_LEARN_VOCABULARY ADD CONSTRAINT TBL_LEARN_VOCABULARY_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_LEARN_VOCABULARY_TBL_UNIT (table: TBL_LEARN_VOCABULARY)
        ALTER TABLE TBL_LEARN_VOCABULARY ADD CONSTRAINT TBL_LEARN_VOCABULARY_TBL_UNIT
            FOREIGN KEY (UNIT_ID)
            REFERENCES TBL_UNIT (UNIT_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_LISTENING_M_LEVEL (table: TBL_LISTENING)
        ALTER TABLE TBL_LISTENING ADD CONSTRAINT TBL_LISTENING_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_MARK_TBL_QUESTION (table: TBL_MARK)
        ALTER TABLE TBL_MARK ADD CONSTRAINT TBL_MARK_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_QA_M_USER (table: TBL_QA)
        ALTER TABLE TBL_QA ADD CONSTRAINT TBL_QA_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_QA_TBL_ANSWER_QA (table: TBL_QA)
        ALTER TABLE TBL_QA ADD CONSTRAINT TBL_QA_TBL_ANSWER_QA
            FOREIGN KEY (QA_ANSWER_ID)
            REFERENCES TBL_ANSWER_QA (ANSWER_QA_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_QA_TBL_QUESTION_QA (table: TBL_QA)
        ALTER TABLE TBL_QA ADD CONSTRAINT TBL_QA_TBL_QUESTION_QA
            FOREIGN KEY (QA_QUESTION_ID)
            REFERENCES TBL_QUESTION_QA (QUESTION_QA_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_RESULT_USER_CHOICE_ANSWER_TBL_ANSWER (table: TBL_RESULT_USER_CHOICE_ANSWER)
        ALTER TABLE TBL_RESULT_USER_CHOICE_ANSWER ADD CONSTRAINT TBL_RESULT_USER_CHOICE_ANSWER_TBL_ANSWER
            FOREIGN KEY (ANSWER_ID)
            REFERENCES TBL_ANSWER (ANSWER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_USER_MARK_M_USER (table: TBL_USER_MARK)
        ALTER TABLE TBL_USER_MARK ADD CONSTRAINT TBL_USER_MARK_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_USER_MARK_TBL_QUESTION (table: TBL_USER_MARK)
        ALTER TABLE TBL_USER_MARK ADD CONSTRAINT TBL_USER_MARK_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_WORD_HISTORY_USER_M_USER (table: TBL_WORD_HISTORY_USER)
        ALTER TABLE TBL_WORD_HISTORY_USER ADD CONSTRAINT TBL_WORD_HISTORY_USER_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_WORD_HISTORY_USER_TBL_WORD_DICTIONARY (table: TBL_WORD_HISTORY_USER)
        ALTER TABLE TBL_WORD_HISTORY_USER ADD CONSTRAINT TBL_WORD_HISTORY_USER_TBL_WORD_DICTIONARY
            FOREIGN KEY (WORD_ID)
            REFERENCES TBL_WORD_DICTIONARY (WORD_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;
-- End of file.
SQL;
       echo  $this->db->query($sql);
    }

    public function down()
    {
        $sql = <<<SQL
        DROP SCHEMA public CASCADE;
        CREATE SCHEMA public;
SQL;
        echo $this->db->query($sql);
    }
}