<?php
        defined('BASEPATH') OR exit('No direct script access allowed');
class Migration_Init extends CI_Migration{
    public function up(){
        $sql=<<<SQL

        -- Created by Vertabelo (http://vertabelo.com)
        -- Last modification date: 2018-09-02 03:00:33.788

        -- tables
        -- Table: M_LEVEL
        CREATE TABLE M_LEVEL (
            LEVEL_ID int  NOT NULL,
            LEVEL_NAME varchar(25) NULL,
            CONSTRAINT M_LEVEL_pk PRIMARY KEY (LEVEL_ID)
        );

        INSERT INTO M_LEVEL(LEVEL_ID, LEVEL_NAME) VALUES (1, 'Beginner');
        INSERT INTO M_LEVEL(LEVEL_ID, LEVEL_NAME) VALUES (2, 'Intermediate');
        INSERT INTO M_LEVEL(LEVEL_ID, LEVEL_NAME) VALUES (3, 'Advanced');

        -- Table: M_USER
        CREATE TABLE M_USER (
            USER_ID serial  NOT NULL,
            USER_NAME varchar(25) NULL,
            EMAIL varchar(255) NULL,
            PASSWORD text NULL,
            BIRTH_DATE varchar(10) NULL,
            GENDER varchar(15) NULL,
            PHONE_NUMBER int NULL,
            ADDRESS varchar(255) NULL,
            ADMIN_FLAG char(1) NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT M_USER_pk PRIMARY KEY (USER_ID)
        );

        -- Table: TBL_ANSWER
        CREATE TABLE TBL_ANSWER (
            ANSWER_ID serial  NOT NULL,
            QUESTION_ID serial NOT NULL,
            USER_ID serial NOT NULL,
            ANSWER_NUMBER int NULL,
            ANSWER_NAME text NULL,
            ANSWER_RESULT int NULL,
            CONSTRAINT TBL_ANSWER_pk PRIMARY KEY (ANSWER_ID)
        );

        -- Table: TBL_ANSWER_QA
        CREATE TABLE TBL_ANSWER_QA (
            ANSWER_QA_ID serial  NOT NULL,
            ANSWER_QA_NAME text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_ANSWER_QA_pk PRIMARY KEY (ANSWER_QA_ID)
        );

        -- Table: TBL_EXAM
        CREATE TABLE TBL_EXAM (
            EXAM_ID serial  NOT NULL,
            LEVEL_ID int  NOT NULL,
            QUESTION_ID serial  NOT NULL,
            EXAM_NAME varchar(50) NULL,
            NUMERICAL_NAME char(2) NULL,
            CONSTRAINT TBL_EXAM_pk PRIMARY KEY (EXAM_ID)
        );

        -- Table: TBL_GRAMMAR
        CREATE TABLE TBL_GRAMMAR (
            GRAMMAR_ID serial  NOT NULL,
            LEVEL_ID int  NOT NULL,
            GRAMMAR_NAME varchar(50) NULL,
            GRAMMAR_DETAILS text NULL,
            DEL_FLAG char(1) NULL,
            CONSTRAINT TBL_GRAMMAR_pk PRIMARY KEY (GRAMMAR_ID)
        );

        -- Table: TBL_LEARN_VOCABULARY
        CREATE TABLE TBL_LEARN_VOCABULARY (
            LEARN_VOCABULARY_ID int  NOT NULL,
            LEVEL_ID int  NOT NULL,
            VOCABULARY_NAME varchar(20) NULL,
            VOCABULARY_MEAN varchar(80) NULL,
            UNIT_ID int NULL,
            SCREEN_ID int NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_LEARN_VOCABULARY_pk PRIMARY KEY (LEARN_VOCABULARY_ID)
        );

        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (1, 1, 'A', 'Một', 1, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (2, 1, 'An', 'Một', 1, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (3, 1, 'About', 'Về', 1, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (4, 1, 'Above', 'Ở trên', 1, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (5, 1, 'Across', 'Ngang qua', 1, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (6, 1, 'Act', 'Hành động, cư xử', 1, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (7, 1, 'Active', 'Năng động, chủ động', 1, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (8, 1, 'Activity', 'Hoạt động', 1, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (9, 1, 'Add', 'Thêm vào, cộng', 1, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (10, 1, 'Afraid', 'Sợ, e rằng', 1, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (11, 1, 'After', 'Sau', 1, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (12, 1, 'Again', 'Lại, một lần nữa', 1, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (13, 1, 'Age', 'Tuổi', 2, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (14, 1, 'Ago', 'Trước đây, về trước', 2, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (15, 1, 'Agree', 'Đồng ý', 2, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (16, 1, 'Air', 'Không khí, không trung', 2, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (17, 1, 'All', 'Tất cả, toàn bộ', 2, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (18, 1, 'Alone', 'Một mình', 2, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (19, 1, 'Along', 'Dọc theo', 2, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (20, 1, 'Already', 'đã, rồi', 2, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (21, 1, 'Always', 'Luôn luôn', 2, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (22, 1, 'Am', 'Là', 2, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (23, 1, 'Are', 'Là', 2, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (24, 1, 'Amount', 'Lượng', 2, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (25, 1, 'And', 'Và', 3, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (26, 1, 'Angry', 'Giận dữ', 3, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (27, 1, 'Any', 'Một vài, một số', 3, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (28, 1, 'Anyone', 'Người nào, ai', 3, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (29, 1, 'Anything', 'Vật gì, việc gì', 3, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (30, 1, 'Anytime', 'Bất kì lúc nào', 3, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (31, 1, 'Another', 'Khác, nữa', 3, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (32, 1, 'Answer', 'Trả lời, câu trả lời', 3, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (33, 1, 'Appear', 'Xuất hiện', 3, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (34, 1, 'Apple', 'Quả táo', 3, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (35, 1, 'Area', 'Khu vực', 3, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (36, 1, 'Arm', 'Cánh tay', 3, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (37, 1, 'Army', 'Quân đội', 4, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (38, 1, 'Around', 'Vòng quanh, xung quanh', 4, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (39, 1, 'Arrive', 'Đến', 4, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (40, 1, 'Art', 'Nghệ thuật', 4, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (41, 1, 'As', 'Khi', 4, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (42, 1, 'Ask', 'Hỏi', 4, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (43, 1, 'At', 'Ở, tại', 4, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (44, 1, 'Attack', 'Tấn công', 4, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (45, 1, 'Aunt', 'Dì, cô, bác', 4, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (46, 1, 'Autumn', 'Mùa thu', 4, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (47, 1, 'Away', 'Xa, cách xa', 4, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (48, 1, 'Baby', 'Trẻ con', 4, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (49, 1, 'Back', 'Sau, trở lại', 5, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (50, 1, 'Bad', 'Tồi tệ', 5, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (51, 1, 'Bag', 'Túi', 5, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (52, 1, 'Ball', 'Bóng', 5, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (53, 1, 'Bank', 'Ngân hàng', 5, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (54, 1, 'Basket', 'Giỏ', 5, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (55, 1, 'Bath', 'Tắm', 5, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (56, 1, 'Bean', 'Đậu, đỗ', 5, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (57, 1, 'Bear', 'Gấu', 5, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (58, 1, 'Beer', 'Bia', 5, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (59, 1, 'Bed', 'giường', 5, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (60, 1, 'Bedroom', 'Phòng ngủ', 5, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (61, 1, 'Be', 'Thì, là', 6, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (62, 1, 'Behave', 'Cư xử, hành vi', 6, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (63, 1, 'Before', 'Trước', 6, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (64, 1, 'Begin', 'Bắt đầu', 6, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (65, 1, 'Behind', 'Đằng sau', 6, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (66, 1, 'Below', 'Ở dưới', 6, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (67, 1, 'Besides', 'Ngoài, bên cạnh', 6, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (68, 1, 'Best', 'Tốt nhất', 6, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (69, 1, 'Better', 'Tốt hơn', 6, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (70, 1, 'Between', 'Ở giữa', 6, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (71, 1, 'Bell', 'Chuông', 6, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (72, 1, 'Big', 'To, lớn', 6, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (73, 1, 'Bird', 'Con chim', 7, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (74, 1, 'Birth', 'Sự sinh đẻ', 7, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (75, 1, 'Birthday', 'Sinh nhật', 7, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (76, 1, 'Bit', 'Một mẩu, một mảnh, một ít', 7, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (77, 1, 'Bite', 'Cắn', 7, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (78, 1, 'Black', 'Màu đen', 7, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (79, 1, 'Bleed', 'Chảy máu', 7, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (80, 1, 'Blood', 'Máu', 7, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (81, 1, 'Block', 'Khối, tòa nhà', 7, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (82, 1, 'Blue', 'Màu xanh da trời', 7, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (83, 1, 'Board', 'Bảng', 7, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (84, 1, 'Boat', 'Thuyền', 7, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (85, 1, 'Body', 'Cơ thể', 8, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (86, 1, 'Bone', 'Xương', 8, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (87, 1, 'Book', 'Sách', 8, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (88, 1, 'Border', 'Biên giới', 8, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (89, 1, 'Bottle', 'Chai, lọ', 8, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (90, 1, 'Bowl', 'Bát', 8, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (91, 1, 'Born', 'Sinh ra', 8, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (92, 1, 'Blow', 'Thổi', 8, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (93, 1, 'Boil', 'Đun, sôi', 8, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (94, 1, 'Borrow', 'Mượn', 8, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (95, 1, 'Breathe', 'Thở', 8, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (96, 1, 'Bring', 'Mang', 8, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (97, 1, 'Brush', 'Chải (tóc), quét, đánh (răng)', 9, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (98, 1, 'Build', 'Xây dựng', 9, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (99, 1, 'Burn', 'Cháy', 9, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (100, 1, 'Buy', 'Mua', 9, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (101, 1, 'Both', 'Cả hai', 9, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (102, 1, 'Bottom', 'Phần dưới cùng, đáy', 9, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (103, 1, 'Box', 'Hộp', 9, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (104, 1, 'Boy', 'Cậu bé', 9, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (105, 1, 'Branch', 'Nhánh, chi', 9, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (106, 1, 'Brave', 'Dũng cảm', 9, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (107, 1, 'Bread', 'Bánh mỳ', 9, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (108, 1, 'Break', 'Làm vỡ', 9, 12, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (109, 1, 'Breakfast', 'Bữa sáng', 10, 1, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (110, 1, 'Bridge', 'Cây cầu', 10, 2, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (111, 1, 'Base', 'Dựa vào', 10, 3, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (112, 1, 'Bright', 'Sáng suốt, thông minh', 10, 4, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (113, 1, 'Beautiful', 'Đẹp', 10, 5, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (114, 1, 'Brother', 'Anh em', 10, 6, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (115, 1, 'Brown', 'Màu nâu', 10, 7, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (116, 1, 'Business', 'Kinh doanh, công tác, công việc', 10, 8, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (117, 1, 'Bus', 'Xe buýt', 10, 9, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (118, 1, 'Busy', 'Bận rộn', 10, 10, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (119, 1, 'But', 'Nhưng', 10, 11, '0');
        INSERT INTO TBL_LEARN_VOCABULARY(LEARN_VOCABULARY_ID, LEVEL_ID, VOCABULARY_NAME, VOCABULARY_MEAN, UNIT_ID, SCREEN_ID, DEL_FG) VALUES (120, 1, 'By', 'Bằng, bởi', 10, 12, '0');

        -- Table: TBL_UNIT
        CREATE TABLE TBL_UNIT(
            UNIT_ID int NOT NULL,
            UNIT_NAME varchar(20) NULL,
            CONSTRAINT TBL_UNIT_pk PRIMARY KEY (UNIT_ID)
        );

        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (1, 'UNIT 1');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (2, 'UNIT 2');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (3, 'UNIT 3');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (4, 'UNIT 4');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (5, 'UNIT 5');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (6, 'UNIT 6');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (7, 'UNIT 7');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (8, 'UNIT 8');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (9, 'UNIT 9');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (10, 'UNIT 10');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (11, 'UNIT 11');
        INSERT INTO TBL_UNIT(UNIT_ID, UNIT_NAME) VALUES (12, 'UNIT 12');

        -- Table: TBL_LISTENING
        CREATE TABLE TBL_LISTENING (
            LISTENING_ID serial  NOT NULL,
            LEVEL_ID int  NOT NULL,
            LISTENING_NAME varchar(50) NULL,
            LINK_MEDIA text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_LISTENING_pk PRIMARY KEY (LISTENING_ID)
        );

        -- Table: TBL_MARK
        CREATE TABLE TBL_MARK (
            QUESTION_ID serial  NOT NULL,
            MARK int NULL
        );

        -- Table: TBL_QA
        CREATE TABLE TBL_QA (
            QA_ID serial  NOT NULL,
            USER_ID serial  NOT NULL,
            QA_ANSWER_ID serial  NOT NULL,
            QA_QUESTION_ID serial  NOT NULL,
            CONSTRAINT TBL_QA_pk PRIMARY KEY (QA_ID)
        );

        -- Table: TBL_QUESTION
        CREATE TABLE TBL_QUESTION (
            QUESTION_ID serial  NOT NULL,
            NUMBER_QUESTION int NULL,
            EXAM_ID serial  NOT NULL,
            QUESTION_NAME varchar(255) NULL,
            QUESTION_SUBTEXT text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_QUESTION_pk PRIMARY KEY (QUESTION_ID)
        );

        -- Table: TBL_QUESTION_QA
        CREATE TABLE TBL_QUESTION_QA (
            QUESTION_QA_ID serial  NOT NULL,
            QUESTION_QA_NAME text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_QUESTION_QA_pk PRIMARY KEY (QUESTION_QA_ID)
        );

        -- Table: TBL_RESULT_USER_CHOICE_ANSWER
        CREATE TABLE TBL_RESULT_USER_CHOICE_ANSWER (
            ANSWER_ID serial  NOT NULL,
            RESULT_USER_CHOICE_ANSWER int NULL
        );

        -- Table: TBL_USER_MARK
        CREATE TABLE TBL_USER_MARK (
            USER_ID serial  NOT NULL,
            QUESTION_ID serial  NOT NULL,
            USER_MARK int NULL
        );

        -- Table: TBL_VOCABULARY_PICTURE
        CREATE TABLE TBL_VOCABULARY_PICTURE (
            VOCABULARY_PICTURE_ID serial  NOT NULL,
            VOCABULARY_NAME varchar(25) NULL,
            VOCABULARY_LINK_PICTURE text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_VOCABULARY_PICTURE_pk PRIMARY KEY (VOCABULARY_PICTURE_ID)
        );

        -- Table: TBL_WORD_DICTIONARY
        CREATE TABLE TBL_WORD_DICTIONARY (
            WORD_ID serial  NOT NULL,
            WORD_NAME varchar(20) NULL,
            WORD_DETAILS text NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_WORD_DICTIONARY_pk PRIMARY KEY (WORD_ID)
        );

        -- Table: TBL_WORD_HISTORY_USER
        CREATE TABLE TBL_WORD_HISTORY_USER (
            WORD_HISTORY_USER_ID serial  NOT NULL,
            USER_ID serial  NOT NULL,
            WORD_ID serial  NOT NULL,
            WORD_NAME varchar(20) NULL,
            DEL_FG char(1) NULL,
            CONSTRAINT TBL_WORD_HISTORY_USER_pk PRIMARY KEY (WORD_HISTORY_USER_ID)
        );

        -- foreign keys
        -- Reference: TBL_ANSWER_M_USER (table: TBL_ANSWER)
        ALTER TABLE TBL_ANSWER ADD CONSTRAINT TBL_ANSWER_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_ANSWER_TBL_QUESTION (table: TBL_ANSWER)
        ALTER TABLE TBL_ANSWER ADD CONSTRAINT TBL_ANSWER_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_EXAM_M_LEVEL (table: TBL_EXAM)
        ALTER TABLE TBL_EXAM ADD CONSTRAINT TBL_EXAM_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_EXAM_TBL_QUESTION (table: TBL_EXAM)
        ALTER TABLE TBL_EXAM ADD CONSTRAINT TBL_EXAM_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_GRAMMAR_M_LEVEL (table: TBL_GRAMMAR)
        ALTER TABLE TBL_GRAMMAR ADD CONSTRAINT TBL_GRAMMAR_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_LEARN_VOCABULARY_M_LEVEL (table: TBL_LEARN_VOCABULARY)
        ALTER TABLE TBL_LEARN_VOCABULARY ADD CONSTRAINT TBL_LEARN_VOCABULARY_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_LEARN_VOCABULARY_TBL_UNIT (table: TBL_LEARN_VOCABULARY)
        ALTER TABLE TBL_LEARN_VOCABULARY ADD CONSTRAINT TBL_LEARN_VOCABULARY_TBL_UNIT
            FOREIGN KEY (UNIT_ID)
            REFERENCES TBL_UNIT (UNIT_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_LISTENING_M_LEVEL (table: TBL_LISTENING)
        ALTER TABLE TBL_LISTENING ADD CONSTRAINT TBL_LISTENING_M_LEVEL
            FOREIGN KEY (LEVEL_ID)
            REFERENCES M_LEVEL (LEVEL_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_MARK_TBL_QUESTION (table: TBL_MARK)
        ALTER TABLE TBL_MARK ADD CONSTRAINT TBL_MARK_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_QA_M_USER (table: TBL_QA)
        ALTER TABLE TBL_QA ADD CONSTRAINT TBL_QA_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_QA_TBL_ANSWER_QA (table: TBL_QA)
        ALTER TABLE TBL_QA ADD CONSTRAINT TBL_QA_TBL_ANSWER_QA
            FOREIGN KEY (QA_ANSWER_ID)
            REFERENCES TBL_ANSWER_QA (ANSWER_QA_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_QA_TBL_QUESTION_QA (table: TBL_QA)
        ALTER TABLE TBL_QA ADD CONSTRAINT TBL_QA_TBL_QUESTION_QA
            FOREIGN KEY (QA_QUESTION_ID)
            REFERENCES TBL_QUESTION_QA (QUESTION_QA_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_RESULT_USER_CHOICE_ANSWER_TBL_ANSWER (table: TBL_RESULT_USER_CHOICE_ANSWER)
        ALTER TABLE TBL_RESULT_USER_CHOICE_ANSWER ADD CONSTRAINT TBL_RESULT_USER_CHOICE_ANSWER_TBL_ANSWER
            FOREIGN KEY (ANSWER_ID)
            REFERENCES TBL_ANSWER (ANSWER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_USER_MARK_M_USER (table: TBL_USER_MARK)
        ALTER TABLE TBL_USER_MARK ADD CONSTRAINT TBL_USER_MARK_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_USER_MARK_TBL_QUESTION (table: TBL_USER_MARK)
        ALTER TABLE TBL_USER_MARK ADD CONSTRAINT TBL_USER_MARK_TBL_QUESTION
            FOREIGN KEY (QUESTION_ID)
            REFERENCES TBL_QUESTION (QUESTION_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_WORD_HISTORY_USER_M_USER (table: TBL_WORD_HISTORY_USER)
        ALTER TABLE TBL_WORD_HISTORY_USER ADD CONSTRAINT TBL_WORD_HISTORY_USER_M_USER
            FOREIGN KEY (USER_ID)
            REFERENCES M_USER (USER_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;

        -- Reference: TBL_WORD_HISTORY_USER_TBL_WORD_DICTIONARY (table: TBL_WORD_HISTORY_USER)
        ALTER TABLE TBL_WORD_HISTORY_USER ADD CONSTRAINT TBL_WORD_HISTORY_USER_TBL_WORD_DICTIONARY
            FOREIGN KEY (WORD_ID)
            REFERENCES TBL_WORD_DICTIONARY (WORD_ID)  
            NOT DEFERRABLE 
            INITIALLY IMMEDIATE
        ;
-- End of file.
SQL;
       echo  $this->db->query($sql);
    }

    public function down()
    {
        $sql = <<<SQL
        DROP SCHEMA public CASCADE;
        CREATE SCHEMA public;
SQL;
        echo $this->db->query($sql);
    }
}